# Create a role that allows a user to get, create, and update pods with the names "blue" and "orange"
# in the "default" namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
    name: developer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "create", "update"]
  resourceNames: ["blue", "orange"]